### PR TITLE
Support writing implication by `==>` in terms

### PR DESCRIPTION
**Pull request by shiatsumat**
Support writing logic implication by `==>` in terms, replacing `->` used before.
Because Rust's token streamer interprets `==>` as a juxtaposition of `==` and `>`, the term parser handles `==>` as such.

### CODE REVIEW

**Comment by shiatsumat** [comment]
This PR, at least currently, overwrites `->` for simplicity.
In order to retain both `==>` and `->`, in particular, we should make the token data of `TermImpl` a bit complex.

**Comment by shiatsumat** [comment]
I also added the test `test_term.rs`, based on `test_expr.rs`.
This kind of testing is really useful and should be more eagerly used for debugging this big library, I suppose.

**Comment by xldenis** [comment]
This works for me, make sure to check that it works in Creusot and update our test suite in consequence.

Is there a particular reason for preferring `==>` over `->`? I don't care either way but I'm curious about your opinion.

**Comment by shiatsumat** [comment]
I prefer `==>`, because implications are usually at a high level and should stand out well.
I think `->` looks a bit too weak compared to other connectives like `&&` and `if ... { ... } else { ... }`.

**Comment by shiatsumat** [comment]
I have checked that `==>` works in Creusot in a branch in Creusot (https://github.com/xldenis/creusot/tree/syn-try), which I'm going to merge later.

**Comment by shiatsumat** [comment]
I meant "squash and merge" but I wrongly just merged, so I force-pushed a commit squashing the updates. Sorry!

**Pull request merged**
